### Get all
GET http://localhost:3003/api/blogs

### create. 201 Created
POST http://localhost:3003/api/blogs HTTP/1.1 
content-type: application/json

{
  "title": "The Agrivana Blog",
  "author": "Joe Gardener",
  "url": "https://joegardener.com/blog/",
  "likes": 12
}