### Get all
GET http://localhost:3003/api/blogs

### create. 201 Created
POST http://localhost:3003/api/blogs HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnZXIxIiwiaWQiOiI2NjI4YmVlNmRjZmJjMTQwMWQ4N2Y5NTYiLCJpYXQiOjE3MTM5NjQyNjN9.m2xavYJhcptx8kOMoqcrq_d37mMixhi9cDBHhdCnnsg

{
  "title": "The 3nd Best Blogs",
  "author": "Number 3",
  "url": "https://one.com/blogs/",
  "likes": 103
}

### Get all blogs
GET http://localhost:3003/api/blogs/

### Get 1
GET http://localhost:3003/api/blogs/662231df88a9e42078803f02

### Get all users
GET http://localhost:3003/api/users

### create ok
POST http://localhost:3003/api/users HTTP/1.1 
content-type: application/json

{
  "username": "blogger1",
  "name": "The Best Blogger",
  "password": "12345678"
}

### create without username - returns 400
POST http://localhost:3003/api/users HTTP/1.1 
content-type: application/json

{
  "name": "The Invalid Blogger",
  "password": "12345678"
}

### login
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "blogger1",
  "password": "12345678"
}