### Get all
GET http://localhost:3003/api/blogs

### create. 201 Created
POST http://localhost:3003/api/blogs HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnZXIyNCIsImlkIjoiNjYyOTQ3ZjQ0YTVjYTIxYTZhMTVmY2IwIiwiaWF0IjoxNzEzOTgxNDQ5fQ.0oPHglCjByN07e-R-wWEBTcJnGciMZ6Skglmxg7Q9i4

{
  "title": "The 5th Blogs",
  "author": "Number 4",
  "url": "https://one.com/blogs/",
  "likes": 44
}

### Get all blogs
GET http://localhost:3003/api/blogs/

### Get 1
GET http://localhost:3003/api/blogs/663b37d9024f71055f855386

### Get 1
GET http://localhost:3003/api/blogs/6628bf31c92540b37919cdbc

### update
PUT http://localhost:3003/api/blogs/6628bf31c92540b37919cdbc HTTP/1.1 
content-type: application/json

{
  "user": "6628bee6dcfbc1401d87f956",
  "likes": 124,
  "author": "Number 1",
  "title": "The Best Blog",
  "url": "https://one.com/blog/"
}

### Delete blog - 400 only its creator can delete a blog
DELETE http://localhost:3003/api/blogs/662948624a5ca21a6a15fcb4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnZXIxIiwiaWQiOiI2NjI4YmVlNmRjZmJjMTQwMWQ4N2Y5NTYiLCJpYXQiOjE3MTM5NjQyNjN9.m2xavYJhcptx8kOMoqcrq_d37mMixhi9cDBHhdCnnsg
###  user:  6628bee6dcfbc1401d87f956 - blogger1

### Delete blog - creator blogger24 ok
DELETE http://localhost:3003/api/blogs/66294ef2e8c140d867a0185f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnZXIyNCIsImlkIjoiNjYyOTQ3ZjQ0YTVjYTIxYTZhMTVmY2IwIiwiaWF0IjoxNzEzOTgxNDQ5fQ.0oPHglCjByN07e-R-wWEBTcJnGciMZ6Skglmxg7Q9i4
### 662947f44a5ca21a6a15fcb0 - blogger24

### Get all users
GET http://localhost:3003/api/users

### create ok
POST http://localhost:3003/api/users HTTP/1.1 
content-type: application/json

{
  "username": "blogger24",
  "name": "Blogger 24",
  "password": "12345678"
}

### create without username - returns 400
POST http://localhost:3003/api/users HTTP/1.1 
content-type: application/json

{
  "name": "The Invalid Blogger",
  "password": "12345678"
}

### login
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "blogger1",
  "password": "12345678"
}
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnZXIxIiwiaWQiOiI2NjI4YmVlNmRjZmJjMTQwMWQ4N2Y5NTYiLCJpYXQiOjE3MTM5NjQyNjN9.m2xavYJhcptx8kOMoqcrq_d37mMixhi9cDBHhdCnnsg

### login
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "blogger24",
  "password": "12345678"
}
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnZXIyNCIsImlkIjoiNjYyOTQ3ZjQ0YTVjYTIxYTZhMTVmY2IwIiwiaWF0IjoxNzEzOTgxNDQ5fQ.0oPHglCjByN07e-R-wWEBTcJnGciMZ6Skglmxg7Q9i4